### PR TITLE
Update deal.II to version 8.4.1

### PR DESCRIPTION
**Pull request by jppelteret**
Update deal.II to version 8.4.1. Fixes [compilation issues](https://github.com/dealii/dealii/releases/tag/v8.4.1) with older GCC.

### CODE REVIEW

**Comment by jppelteret** [comment]
@davydden This all seems to work for me :-)

**Comment by davydden** [comment]
cool -)

**Comment by jppelteret** [comment]
Wow, that didn't take long at all ;-)

**Comment by jppelteret** [comment]
I think that might be a record quick merge. Quick with the trigger there, buddy :-)

**Comment by davydden** [comment]
hehe ;-))

**Pull request merged**
