### PR TITLE
[WIP] Update build instructions

### PR DESCRIPTION
**Pull request by jppelteret**
Update of build instructions to include Ubuntu 14.04 desktop installation and Mac OS-X.

### CODE REVIEW

**Comment by jppelteret** [comment]
@davydden Would you like me to get rid of the Linux installation instructions for OpenCascade, which of course don't work at the moment?

**Comment by davydden** [comment]
yes, i would say so, some people may not notice `[IGNORE]` in the header. 

p.s. that's a whole lot of work! Thanks for doing it.

**Comment by jppelteret** [comment]
@davydden You're welcome :-)

So you can see the current state of the readme file [here](https://github.com/jppelteret/homebrew-dealiisuite/tree/update_build_instructions). Is there anything else you'd like changed? If not then I can squash these commits before you merge them.

**Comment by davydden** [comment]
it's all good! If you can, merge it yourself, if not I will merge after you squash.

**Comment by jppelteret** [comment]
@davydden Yay, thats the first PR merge that I've performed. Time to break out the champagne :-)

**Comment by davydden** [comment]
LoL

**Pull request merged**
